### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by humehta** [dair-iitd/OpenIE-standalone#19]
I amtrying to create the stand alone jar by executing the following command:

     sbt clean compile assembly

but I am getting the following error:

Picked up _JAVA_OPTIONS: -Xmx1024M
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Xmx1024M
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] Loading project definition from C:\Users\harsh\OpenIE-standalone\project
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1147)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1264)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1335)
        at sbt.IO$.pathSplit(IO.scala:723)
        at sbt.IO$.parseClasspath(IO.scala:821)
        at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:64)
        at sbt.compiler.AggressiveCompile.withBootclasspath(AggressiveCompile.scala:50)
        at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:83)
        at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
        at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
        at sbt.Compiler$.apply(Compiler.scala:70)
        at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:722)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
[error] (compile:compile) java.lang.NullPointerException

**Comment by swarnaHub** [comment]
How much memory are you allocating? I see 1 GB, which is not enough. Use atleast 10 GB by specifying "-J-Xmx10000M" in the memory options. Go through the ReadMe carefully.

**Comment by humehta** [comment]
I executed the following command:

java -Xmx10g -XX:+UseConcMarkSweepGC -jar C:\Users\harsh\OpenIE-standalone\openie-assembly.jar --format column --include-unknown-arg2 C:\Users\harsh\PycharmProjects\untitled3\to_openIE.txt C:\Users\harsh\PycharmProjects\untitled3\from_openIE.txt

Do you mean to say I need to set the heap space in environment variables to -Xmx10000mM ?

**Comment by swarnaHub** [comment]
Given that you are running this, I am guessing that you were able to build the jar successfully. You can now run it using the command you wrote. Are you not able to?

**Comment by humehta** [comment]
Oh actually the above jar file is the already compiled jar file that is given in this project. Not compiled by me. 
Where do I have to run the sbt clean compile assembly command, in the OpenIE folder right?

**Comment by humehta** [comment]
When I run the above command I get this output:

Picked up _JAVA_OPTIONS: -Xmx4096M
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Xmx4096M
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] Loading project definition from C:\Users\harsh\OpenIE-standalone\project\project
[info] Updating {file:/C:/Users/harsh/OpenIE-standalone/project/project/}openie-standalone-build-build...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
  [info] Resolving org.scala-sbt#sbt;0.13.0 ...
  [info] Resolving org.scala-sbt#main;0.13.0 ...
  [info] Resolving org.scala-sbt#actions;0.13.0 ...
  [info] Resolving org.scala-sbt#classpath;0.13.0 ...
  [info] Resolving org.scala-sbt#launcher-interface;0.13.0 ...
  [info] Resolving org.scala-sbt#interface;0.13.0 ...
  [info] Resolving org.scala-sbt#io;0.13.0 ...
  [info] Resolving org.scala-sbt#control;0.13.0 ...
  [info] Resolving org.scala-lang#scala-compiler;2.10.2 ...
  [info] Resolving org.scala-lang#scala-reflect;2.10.2 ...
  [info] Resolving org.scala-sbt#completion;0.13.0 ...
  [info] Resolving org.scala-sbt#collections;0.13.0 ...
  [info] Resolving jline#jline;2.11 ...
  [info] Resolving org.scala-sbt#api;0.13.0 ...
  [info] Resolving org.scala-sbt#compiler-integration;0.13.0 ...
  [info] Resolving org.scala-sbt#incremental-compiler;0.13.0 ...
  [info] Resolving org.scala-sbt#logging;0.13.0 ...
  [info] Resolving org.scala-sbt#process;0.13.0 ...
  [info] Resolving org.scala-sbt#relation;0.13.0 ...
  [info] Resolving org.scala-sbt#compile;0.13.0 ...
  [info] Resolving org.scala-sbt#persist;0.13.0 ...
  [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
  [info] Resolving org.scala-sbt#classfile;0.13.0 ...
  [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.0 ...
  [info] Resolving org.scala-sbt#ivy;0.13.0 ...
  [info] Resolving org.scala-sbt#cross;0.13.0 ...
  [info] Resolving org.apache.ivy#ivy;2.3.0-rc1 ...
  [info] Resolving com.jcraft#jsch;0.1.46 ...
  [info] Resolving org.scala-sbt#run;0.13.0 ...
  [info] Resolving org.scala-sbt#task-system;0.13.0 ...
  [info] Resolving org.scala-sbt#tasks;0.13.0 ...
  [info] Resolving org.scala-sbt#tracking;0.13.0 ...
  [info] Resolving org.scala-sbt#cache;0.13.0 ...
  [info] Resolving org.scala-sbt#testing;0.13.0 ...
  [info] Resolving org.scala-sbt#test-agent;0.13.0 ...
  [info] Resolving org.scala-sbt#test-interface;1.0 ...
  [info] Resolving org.scala-sbt#main-settings;0.13.0 ...
  [info] Resolving org.scala-sbt#apply-macro;0.13.0 ...
  [info] Resolving org.scala-sbt#command;0.13.0 ...
  [info] Resolving org.scala-sbt#compiler-interface;0.13.0 ...
  [info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.0 ...
  [info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.0 ...
  [info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.0 ...
  [info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
  [info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
  [info] Resolving org.scala-lang#jline;2.10.6 ...
  [info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1147)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1264)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1335)
        at sbt.IO$.pathSplit(IO.scala:723)
        at sbt.IO$.parseClasspath(IO.scala:821)
        at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:64)
        at sbt.compiler.AggressiveCompile.withBootclasspath(AggressiveCompile.scala:50)
        at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:83)
        at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
        at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
        at sbt.Compiler$.apply(Compiler.scala:70)
        at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:722)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
[error] (compile:compile) java.lang.NullPointerException

**Comment by humehta** [comment]
But also first there was no assembly.sbt file in the project, so I created one because it was giving me an eror that no object found:assembly.

**Comment by swarnaHub** [comment]
Run "sbt -J-Xmx10000M clean compile assembly" in your base folder. You don't need an assembly.sbt. build.sbt should take care of all dependencies. If you can't build the jar, download the one that I have already shared in the "Using pre-compiled OpenIE standalone jar" section of the ReadMe.

**Comment by humehta** [comment]
I ran the below command:
java -Xmx10g -XX:+UseConcMarkSweepGC -jar C:\Users\harsh\OpenIE-standalone\openie-assembly.jar --format column --include-unknown-arg2 C:\Users\harsh\PycharmProjects\untitled3\to_openIE.txt C:\Users\harsh\PycharmProjects\untitled3\from_openIE.txt

I got the following error:

Picked up _JAVA_OPTIONS: -Xmx1024M
Loading feature templates.
Loading models.
Loading lexica.
Loading configuration.
Loading feature templates.
Loading models.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.lang.reflect.Array.newArray(Native Method)
        at java.lang.reflect.Array.newInstance(Unknown Source)
        at java.io.ObjectInputStream.readArray(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
        at java.io.ObjectInputStream.readSerialData(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.readArray(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.readObject(Unknown Source)
        at com.clearnlp.component.AbstractStatisticalComponent.loadDefault(AbstractStatisticalComponent.java:200)
        at com.clearnlp.component.dep.AbstractDEPParser.load(AbstractDEPParser.java:126)
        at com.clearnlp.component.AbstractStatisticalComponent.<init>(AbstractStatisticalComponent.java:120)
        at com.clearnlp.component.AbstractStatisticalComponentSB.<init>(AbstractStatisticalComponentSB.java:95)
        at com.clearnlp.component.dep.AbstractDEPParser.<init>(AbstractDEPParser.java:106)
        at com.clearnlp.component.dep.EnglishDEPParser.<init>(EnglishDEPParser.java:91)
        at com.clearnlp.nlp.NLPGetter.getDEPParser(NLPGetter.java:199)
        at com.clearnlp.nlp.NLPGetter.getComponent(NLPGetter.java:161)
        at com.clearnlp.nlp.NLPGetter.getComponent(NLPGetter.java:147)
        at edu.knowitall.tool.parse.ClearParser.<init>(ClearParser.scala:43)
        at edu.knowitall.openie.OpenIECli$Config.createParser(OpenIECli.scala:122)
        at edu.knowitall.openie.OpenIECli$.run(OpenIECli.scala:194)
        at edu.knowitall.openie.OpenIECli$delayedInit$body.apply(OpenIECli.scala:176)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at edu.knowitall.openie.OpenIECli$.main(OpenIECli.scala:30)

**Comment by humehta** [comment]
It did not work with the above compile commnad but I am trying to use the already compiled one you have provided. Also I allocated 10G in the Java_Options environment variable.

**Comment by swarnaHub** [comment]
The error "Picked up _JAVA_OPTIONS: -Xmx1024M" shows that it is using only 1 GB of heap space. You would need to fix this so that it picks up the 10 GB that you are specifying in the options.

**Comment by humehta** [comment]
Yes I did that! 
I guess OpenIE worked but got stuck at the following exception:

Picked up _JAVA_OPTIONS: -Xmx10G
Loading feature templates.
Loading models.
Loading lexica.
Loading configuration.
Loading feature templates.
Loading models.
Loading feature templates.
Loading models.
Loading lexica.
Loading feature templates.
Loading models.
Loading feature templates.
Loading models.
Loading lexica.
Loading feature templates.
Loading models.
Loading lexica.
Initializing Language Model
* * * * * * * * * * * * *
* OpenIE 5.0 is ready *
* * * * * * * * * * * * *
Processing file: C:\Users\harsh\PycharmProjects\untitled3\to_openIE.txt
java.lang.NullPointerException
        at edu.illinois.cs.cogcomp.quant.standardize.Numbers.extractNumberFromTokenizedWords(Numbers.java:210)
        at edu.illinois.cs.cogcomp.quant.standardize.Numbers.extractNumberFromWords(Numbers.java:305)
        at edu.illinois.cs.cogcomp.quant.standardize.Numbers.extractNumber(Numbers.java:271)
        at edu.illinois.cs.cogcomp.quant.standardize.Quantity.extractQuantity(Quantity.java:30)
        at edu.illinois.cs.cogcomp.quant.standardize.Normalizer.parse(Normalizer.java:50)
        at edu.illinois.cs.cogcomp.quant.driver.Quantifier.getSpans(Quantifier.java:115)
        at edu.iitd.cse.open_nre.onre.helper.OnreHelper_DanrothQuantifier.getQuantitiesDanroth(OnreHelper_DanrothQuantifier.java:123)
        at edu.iitd.cse.open_nre.onre.helper.MayIHelpYou.runMe(MayIHelpYou.java:36)
        at edu.knowitall.openie.OpenIE.extract(OpenIE.scala:73)
        at edu.knowitall.openie.OpenIE.extract(OpenIE.scala:61)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4$$anonfun$apply$6.apply(OpenIECli.scala:227)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4$$anonfun$apply$6.apply(OpenIECli.scala:222)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4.apply(OpenIECli.scala:222)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4.apply(OpenIECli.scala:214)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:86)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
        at scala.util.control.Exception$Catch.either(Exception.scala:124)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:86)
        at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
        at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:48)
        at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:45)
        at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:48)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply(OpenIECli.scala:214)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply(OpenIECli.scala:213)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:86)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
        at scala.util.control.Exception$Catch.either(Exception.scala:124)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:86)
        at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
        at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:48)
        at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:45)
        at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:48)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply$mcV$sp(OpenIECli.scala:213)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply(OpenIECli.scala:213)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply(OpenIECli.scala:213)
        at edu.knowitall.common.Timing$.time(Timing.scala:50)
        at edu.knowitall.common.Timing$.timeThen(Timing.scala:72)
        at edu.knowitall.openie.OpenIECli$.run(OpenIECli.scala:241)
        at edu.knowitall.openie.OpenIECli$delayedInit$body.apply(OpenIECli.scala:176)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at edu.knowitall.openie.OpenIECli$.main(OpenIECli.scala:30)
        at edu.knowitall.openie.OpenIECli.main(OpenIECli.scala)

Any idea?

**Comment by swarnaHub** [comment]
Pass the option "--ignore-errors". It will ignore all exceptions.

**Comment by humehta** [comment]
Okay!

**Comment by swarnaHub** [comment]
Let me know if this worked. I'll close the issue.

**Comment by humehta** [comment]
Where do I put this option in the above command because I still get the errors and exception:
I executed the following command:
java -Xmx10g -XX:+UseConcMarkSweepGC -jar C:\Users\harsh\OpenIE-standalone\openie-assembly.jar --format column --include-unknown-arg2 --ignore-errors C:\Users\harsh\PycharmProjects\untitled3\to_openIE.txt C:\Users\harsh\PycharmProjects\untitled3\from_openIE.txt

**Comment by humehta** [comment]
Giving the following error:



Processing file: C:\Users\harsh\PycharmProjects\untitled3\to_openIE.txt
java.lang.NullPointerException
        at edu.illinois.cs.cogcomp.quant.standardize.Numbers.extractNumberFromTokenizedWords(Numbers.java:210)
        at edu.illinois.cs.cogcomp.quant.standardize.Numbers.extractNumberFromWords(Numbers.java:305)
        at edu.illinois.cs.cogcomp.quant.standardize.Numbers.extractNumber(Numbers.java:271)
        at edu.illinois.cs.cogcomp.quant.standardize.Quantity.extractQuantity(Quantity.java:30)
        at edu.illinois.cs.cogcomp.quant.standardize.Normalizer.parse(Normalizer.java:50)
        at edu.illinois.cs.cogcomp.quant.driver.Quantifier.getSpans(Quantifier.java:115)
        at edu.iitd.cse.open_nre.onre.helper.OnreHelper_DanrothQuantifier.getQuantitiesDanroth(OnreHelper_DanrothQuantifier.java:123)
        at edu.iitd.cse.open_nre.onre.helper.MayIHelpYou.runMe(MayIHelpYou.java:36)
        at edu.knowitall.openie.OpenIE.extract(OpenIE.scala:73)
        at edu.knowitall.openie.OpenIE.extract(OpenIE.scala:61)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4$$anonfun$apply$6.apply(OpenIECli.scala:227)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4$$anonfun$apply$6.apply(OpenIECli.scala:222)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4.apply(OpenIECli.scala:222)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4.apply(OpenIECli.scala:214)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:86)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
        at scala.util.control.Exception$Catch.either(Exception.scala:124)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:86)
        at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
        at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:48)
        at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:45)
        at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:48)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply(OpenIECli.scala:214)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply(OpenIECli.scala:213)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:86)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
        at scala.util.control.Exception$Catch.either(Exception.scala:124)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:86)
        at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
        at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:48)
        at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:45)
        at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:48)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply$mcV$sp(OpenIECli.scala:213)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply(OpenIECli.scala:213)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply(OpenIECli.scala:213)
        at edu.knowitall.common.Timing$.time(Timing.scala:50)
        at edu.knowitall.common.Timing$.timeThen(Timing.scala:72)
        at edu.knowitall.openie.OpenIECli$.run(OpenIECli.scala:241)
        at edu.knowitall.openie.OpenIECli$delayedInit$body.apply(OpenIECli.scala:176)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at edu.knowitall.openie.OpenIECli$.main(OpenIECli.scala:30)
        at edu.knowitall.openie.OpenIECli.main(OpenIECli.scala)
1530811689881 - Error on direct access in noun data file: check CR/LF endings
1530812176608 - Error on direct access in verb data file: check CR/LF endings
1530812176609 - Error on direct access in adverb data file: check CR/LF endings
1530812176611 - Error on direct access in adjective data file: check CR/LF endings
1530812180239 - Error on direct access in noun data file: check CR/LF endings
1530812180240 - Error on direct access in verb data file: check CR/LF endings
1530812180240 - Error on direct access in adverb data file: check CR/LF endings
1530812180241 - Error on direct access in adjective data file: check CR/LF endings

**Comment by swarnaHub** [comment]
It seems your input file has issues with line endings. You would need to put one sentence per line. Also, these issues arise when the line encodings are not consistent with the platform. Try with some sample sentences and see if it works.

**Comment by humehta** [comment]
Thanks man it worked! It was the '\n' at the end of the sentence that was causing the problem because it was a jar of Linux that I was using.

**Comment by swarnaHub** [comment]
Great! Are you running it on windows?

**Comment by humehta** [comment]
Yes.

**Comment by swarnaHub** [comment]
Cool! Closing the issue now.
