### ISSUE TITLE
Error while executing the latest build.

### ISSUE THREAD

**Issue by newmluser** [dair-iitd/OpenIE-standalone#34]
Can you please let me know if I am missing anything
* * * * * * * * * * * * *

Error on sentence: [0054] Each paint thus prepared was coated on a cold-rolled steel plate: JIS G3141 SPCC-SB (150╫70╫1.0
Exception in thread "main" java.util.regex.PatternSyntaxException: Unclosed group near index 77
(?i).*\bon a cold - rolled steel plate : JIS G3141 SPCC - SB ( 150╫70╫1.0\b.*
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.accept(Unknown Source)
        at java.util.regex.Pattern.group0(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.matches(Unknown Source)
        at java.lang.String.matches(Unknown Source)
        at edu.iitd.cse.open_nre.onre.utils.OnreUtils_string.isIgnoreCaseContainsPhrase(OnreUtils_string.java:11)
        at edu.iitd.cse.open_nre.onre.helper.OnreHelper_PostProcessing.removeAdditionalInfoIfAlreadyPresent(OnreHelper_PostProcessing.java:173)
        at edu.iitd.cse.open_nre.onre.helper.OnreHelper_PostProcessing.postProcessingHelper_isAdditionalInfoAlreadyPresent(OnreHelper_PostProcessing.java:167)
        at edu.iitd.cse.open_nre.onre.helper.OnreHelper_PostProcessing.onreExtraction_postProcessing(OnreHelper_PostProcessing.java:36)
        at edu.iitd.cse.open_nre.onre.helper.MayIHelpYou.getExtraction(MayIHelpYou.java:132)
        at edu.iitd.cse.open_nre.onre.helper.MayIHelpYou.getExtractions(MayIHelpYou.java:110)
        at edu.iitd.cse.open_nre.onre.helper.MayIHelpYou.runMe(MayIHelpYou.java:46)
        at edu.iitd.cse.open_nre.onre.helper.MayIHelpYou.runMe(MayIHelpYou.java:39)
        at edu.knowitall.openie.OpenIE.extract(OpenIE.scala:177)
        at edu.knowitall.openie.OpenIE.extract(OpenIE.scala:62)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4$$anonfun$apply$6.apply(OpenIECli.scala:227)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4$$anonfun$apply$6.apply(OpenIECli.scala:222)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4.apply(OpenIECli.scala:222)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$4.apply(OpenIECli.scala:214)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:86)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
        at scala.util.control.Exception$Catch.either(Exception.scala:124)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:86)
        at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
        at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:48)
        at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:45)
        at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:48)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply(OpenIECli.scala:214)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply(OpenIECli.scala:213)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:86)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
        at scala.util.control.Exception$Catch.either(Exception.scala:124)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:86)
        at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
        at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:48)
        at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:45)
        at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:48)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply$mcV$sp(OpenIECli.scala:213)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply(OpenIECli.scala:213)
        at edu.knowitall.openie.OpenIECli$$anonfun$run$1.apply(OpenIECli.scala:213)
        at edu.knowitall.common.Timing$.time(Timing.scala:50)
        at edu.knowitall.common.Timing$.timeThen(Timing.scala:72)
        at edu.knowitall.openie.OpenIECli$.run(OpenIECli.scala:241)
        at edu.knowitall.openie.OpenIECli$delayedInit$body.apply(OpenIECli.scala:176)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at edu.knowitall.openie.OpenIECli$.main(OpenIECli.scala:30)
        at edu.knowitall.openie.OpenIECli.main(OpenIECli.scala)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 9642 s, completed Aug 27, 2019 12:01:43 PM

**Comment by vaibhavad** [comment]
This error is probably from encountering some special characters or symbols which throw an error during pattern matching. It can be resolved in two ways = 

1) Pre-process the input data to remove special characters

2) Try to run it with --ignore-errors flag

**Comment by vaibhavad** [comment]
@newmluser Are you able to run it with the suggested fix?

**Comment by francesfeng** [comment]
I had similar issues. Check your sentences if contain quotation marks, seems "" is the reason causing errors.
