### ISSUE TITLE
unresolved dependency: edu.iitd.cse.open_nre.onre#onre_2.10;1.0.0-SNAPSHOT: not found

### ISSUE THREAD

**Issue by usbader** [dair-iitd/OpenIE-standalone#48]
Hello all, 

I am trying to compile openie, but the following error arises. I will include all logs. Can you please help?

[info] Set current project to onre (in build file:/home/usbader/OpenIE-standalone/ONRE/)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/home/usbader/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.16/ivy-0.13.16.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] :: delivering :: edu.iitd.cse.open_nre.onre#onre_2.10;1.0.0-SNAPSHOT :: 1.0.0-SNAPSHOT :: integration :: Sat Jul 18 20:02:28 UTC 2020
[info] 	delivering ivy file to /home/usbader/OpenIE-standalone/ONRE/target/scala-2.10/ivy-1.0.0-SNAPSHOT.xml
[info] Wrote /home/usbader/OpenIE-standalone/ONRE/target/scala-2.10/onre_2.10-1.0.0-SNAPSHOT.pom
[info] Compiling 32 Java sources to /home/usbader/OpenIE-standalone/ONRE/target/scala-2.10/classes...
[info] Main Java API documentation to /home/usbader/OpenIE-standalone/ONRE/target/scala-2.10/api...
[error] javadoc: error - invalid flag: -d
[error] Usage: javadoc [options] [packagenames] [sourcefiles] [@files]
[error]   -overview <file>                 Read overview documentation from HTML file
[error]   -public                          Show only public classes and members
[error]   -protected                       Show protected/public classes and members (default)
[error]   -package                         Show package/protected/public classes and members
[error]   -private                         Show all classes and members
[error]   --help                           Display command line options and exit
[error]   -doclet <class>                  Generate output via alternate doclet
[error]   -docletpath <path>               Specify where to find doclet class files
[error]   --module-source-path <path>      Specify where to find input source files for multiple modules
[error]   --upgrade-module-path <path>     Override location of upgradeable modules
[error]   --module-path <path>, -p <path>  Specify where to find application modules
[error]   --add-modules <module>(,<module>)*
[error]                                    Root modules to resolve in addition to the initial modules,
[error]                                    or all modules on the module path if <module> is ALL-MODULE-PATH.
[error]   --limit-modules <module>(,<module>)*
[error]                                    Limit the universe of observable modules
[error]   --source-path <path>             Specify where to find source files
[error]   -sourcepath <path>               Specify where to find source files
[error]   --class-path <path>              Specify where to find user class files
[error]   -classpath <path>                Specify where to find user class files
[error]   -cp <path>                       Specify where to find user class files
[error]   -exclude <pkglist>               Specify a list of packages to exclude
[error]   -subpackages <subpkglist>        Specify subpackages to recursively load
[error]   -breakiterator                   Compute first sentence with BreakIterator
[error]   -bootclasspath <path>            Override location of platform class files
[error]                                    used for non-modular releases
[error]   --system <jdk>                   Override location of system modules used
[error]                                    for modular releases.
[error]   -source <release>                Provide source compatibility with specified release
[error]   --release <release>              Provide source compatibility with specified release
[error]   -extdirs <dirlist>               Override location of installed extensions
[error]   -verbose                         Output messages about what Javadoc is doing
[error]   -locale <name>                   Locale to be used, e.g. en_US or en_US_WIN
[error]   -encoding <name>                 Source file encoding name
[error]   -quiet                           Do not display status messages
[error]   -J<flag>                         Pass <flag> directly to the runtime system
[error]   -X                               Print a synopsis of nonstandard options and exit
[error] 
[error] 
[error] GNU-style options may use = instead whitespace to separate the name of an option
[error] from its value.
[error] 
[error] 1 error
[info] Packaging /home/usbader/OpenIE-standalone/ONRE/target/scala-2.10/onre_2.10-1.0.0-SNAPSHOT.jar ...
[info] Done packaging.
[error] (compile:doc) javadoc returned nonzero exit code
[error] Total time: 7 s, completed Jul 18, 2020, 8:02:35 PM
[info] Loading settings for project openie-standalone-build from plugins.sbt ...
[info] Loading project definition from /home/usbader/OpenIE-standalone/project
[info] Loading settings for project openie-standalone from version.sbt,build.sbt ...
[info] Set current project to openie (in build file:/home/usbader/OpenIE-standalone/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating ...
[warn] Resolving a snapshot version. It's going to be slow unless you use `updateOptions := updateOptions.value.withLatestSnapshots(false)` options.
[info] Out of 1 candidates we found for edu.washington.cs.knowitall.srlie#srlie_2.10;1.0.4-SNAPSHOT in local, we are choosing local.
[warn] 	module not found: edu.iitd.cse.open_nre.onre#onre_2.10;1.0.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/usbader/.ivy2/local/edu.iitd.cse.open_nre.onre/onre_2.10/1.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/edu/iitd/cse/open_nre/onre/onre_2.10/1.0.0-SNAPSHOT/onre_2.10-1.0.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/usbader/.sbt/preloaded/edu.iitd.cse.open_nre.onre/onre_2.10/1.0.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/usbader/.sbt/preloaded/edu/iitd/cse/open_nre/onre/onre_2.10/1.0.0-SNAPSHOT/onre_2.10-1.0.0-SNAPSHOT.pom
[warn] ==== Sonatype SNAPSHOTS: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/edu/iitd/cse/open_nre/onre/onre_2.10/1.0.0-SNAPSHOT/onre_2.10-1.0.0-SNAPSHOT.pom
[warn] ==== bintray-com.eed3si9n-sbt-plugins: tried
[warn]   https://dl.bintray.com/com.eed3si9n/sbt-plugins/edu.iitd.cse.open_nre.onre/onre_2.10/1.0.0-SNAPSHOT/ivys/ivy.xml
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: edu.iitd.cse.open_nre.onre#onre_2.10;1.0.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		edu.iitd.cse.open_nre.onre:onre_2.10:1.0.0-SNAPSHOT (/home/usbader/OpenIE-standalone/build.sbt#L26-45)
[warn] 		  +- edu.washington.cs.knowitall.openie:openie_2.10:5.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: edu.iitd.cse.open_nre.onre#onre_2.10;1.0.0-SNAPSHOT: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2539)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: edu.iitd.cse.open_nre.onre#onre_2.10;1.0.0-SNAPSHOT: not found
[error] Total time: 7 s, completed Jul 18, 2020, 8:02:54 PM

**Comment by tensor2077** [comment]
Will this helpful? 
https://github.com/dair-iitd/OpenIE-standalone/issues/46#issuecomment-671714571

**Comment by lujiaying** [comment]
Get the same error that can not successfully execute
`$ sbt publishLocal` under `ONRE` directory

**Comment by GillesJ** [comment]
Same problem here, looks like the ONRE dependency does not live in the repos any longer edu.iitd.cse.open_nre.onre#onre_2.10;1.0.0-SNAPSHOT

Any ideas where to get this?

**Comment by farshad68** [comment]
I also have the same problem, could anybody find the file? 
could anybody build the project ?


```
Note: Unresolved dependencies path:
          edu.iitd.cse.open_nre.onre:onre_2.10:1.0.0-SNAPSHOT (/home/syfact/OpenIE-standalone/build.sbt#L26-45)
            +- edu.washington.cs.knowitall.openie:openie_2.10:5.0-SNAPSHOT
```
