### ISSUE TITLE
Building JAR: deduplicate: different file contents found in the following

### ISSUE THREAD

**Issue by larswise** [dair-iitd/OpenIE-standalone#54]
when I try to package to jar, I get the following errors:

Any tips?

[error] 2 errors were encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] /home/lars/kge/OpenIE-standalone/lib/BONIE.jar:edu/iitd/cse/open_nre/onre/utils/WordNet-3.0/lib/wnres/wnb.man
[error] /home/lars/.ivy2/local/edu.iitd.cse.open_nre.onre/onre_2.10/1.0.0-SNAPSHOT/jars/onre_2.10.jar:edu/iitd/cse/open_nre/onre/utils/WordNet-3.0/lib/wnres/wnb.man
[error] deduplicate: different file contents found in the following:
[error] /home/lars/kge/OpenIE-standalone/lib/BONIE.jar:edu/iitd/cse/open_nre/onre/utils/WordNet-3.0/lib/wnres/wngloss.man
[error] /home/lars/.ivy2/local/edu.iitd.cse.open_nre.onre/onre_2.10/1.0.0-SNAPSHOT/jars/onre_2.10.jar:edu/iitd/cse/open_nre/onre/utils/WordNet-3.0/lib/wnres/wngloss.man
[error]         at sbtassembly.Assembly$.applyStrategies(Assembly.scala:141)
[error]         at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error]         at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error]         at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error]         at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error]         at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
[error]         at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
[error]         at sbtassembly.Assembly$.apply(Assembly.scala:84)
[error]         at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:249)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (assembly) deduplicate: different file contents found in the following:
[error] /home/lars/kge/OpenIE-standalone/lib/BONIE.jar:edu/iitd/cse/open_nre/onre/utils/WordNet-3.0/lib/wnres/wnb.man
[error] /home/lars/.ivy2/local/edu.iitd.cse.open_nre.onre/onre_2.10/1.0.0-SNAPSHOT/jars/onre_2.10.jar:edu/iitd/cse/open_nre/onre/utils/WordNet-3.0/lib/wnres/wnb.man
[error] deduplicate: different file contents found in the following:
[error] /home/lars/kge/OpenIE-standalone/lib/BONIE.jar:edu/iitd/cse/open_nre/onre/utils/WordNet-3.0/lib/wnres/wngloss.man
[error] /home/lars/.ivy2/local/edu.iitd.cse.open_nre.onre/onre_2.10/1.0.0-SNAPSHOT/jars/onre_2.10.jar:edu/iitd/cse/open_nre/onre/utils/WordNet-3.0/lib/wnres/wngloss.man
[error] Total time: 122 s, completed Feb 6, 2021 3:56:00 PM

**Comment by larswise** [comment]
I had a python script in the datacatalog to download the language model, removed it and this error went away.
